[package]
name = "otp-uinput"
version = "0.1.0"
authors = ["jingjiezhuang <jingjie.zhuang@igg.com>"]
edition = "2018"

[dependencies]
futures = "^0.1"
tokio = "^0.1"
tokio-io = "^0.1"
tokio-core = "^0.1"
tokio-uds = "^0.2"
bytes = "^0.4"
uinput = "^0.1"